In [4]:
#1
import numpy as np
a=np.array([10,20,30,40,50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [5]:
#2
b=np.array(([1,2],[3,4],[4,5]))
print(b)

[[1 2]
 [3 4]
 [4 5]]


In [6]:
#3
c=np.array([7,8,9])
print(c)
print(c.dtype)


[7 8 9]
int64


In [7]:
#4
print(np.zeros(6))
print(np.ones((3,2),dtype=int))

[0. 0. 0. 0. 0. 0.]
[[1 1]
 [1 1]
 [1 1]]


In [8]:
#5
print(np.empty((2,2)))

#because due to present of already used values in the memory locations 
#because it will be faster as it skips initialization time 

[[0.00000000e+000 1.19009312e-311]
 [1.19009312e-311 1.19009312e-311]]


In [9]:
#6
print(np.arange(0,20,2))
print(np.linspace(0,1,6))

# the difference between arange() and linspace() is thatin arange() ending value is exclusive and in linspace() the end value is inclusive.

[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.2 0.4 0.6 0.8 1. ]


In [10]:
#7
print(np.random.random((3,3)))

[[0.77100243 0.97386757 0.79996108]
 [0.68944014 0.79445114 0.46404283]
 [0.81446363 0.22959309 0.7192246 ]]
