In [4]:
#1
import numpy as np
arr=np.arange(21)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(21,)
21
int64


In [5]:
#2
np.random.seed(1)
array=np.random.randint(50,size=(4,5))
print(array)
array.nbytes
array.itemsize

[[37 43 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 45  6]
 [25 20 37 18 20]]


4

In [14]:
#3
arr=np.arange(1,13).reshape(3,4)
print(arr)

print(arr[1])
print(arr[:,2])

print(arr[-1,:])

print(arr[:,-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[ 3  7 11]
[ 9 10 11 12]
[ 4  8 12]


In [20]:
#4
arr=np.random.randint(50,(3,4))
print(arr)

[[11 42 28 29]
 [14  4 23 23]
 [41 49 30 32]]


In [2]:
import numpy as np
my_list = [10, 20, 30, 40, 50]
my_array = np.array(my_list)
print("Array:", my_array)
print("Type:", type(my_array))

Array: [10 20 30 40 50]
Type: <class 'numpy.ndarray'>


In [4]:
import numpy as np
my_matrix = np.arange(1, 7).reshape(2, 3)
print("Matrix:\n", my_matrix)
print("Type:", type(my_matrix))

Matrix:
 [[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>


In [5]:
import numpy as np
arr = np.empty((2, 2))
print("Array:\n", arr)
print("Type:", type(arr))

Array:
 [[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 7.16703010e-312]]
Type: <class 'numpy.ndarray'>
