In [3]:
import numpy as np

my_list = [10, 20, 30, 40, 50]

my_array = np.array(my_list)

print("Array:", my_array)


print("Type:", type(my_array))


Array: [10 20 30 40 50]
Type: <class 'numpy.ndarray'>


In [4]:
import numpy as np

my_matrix = np.arange(1, 7).reshape(2, 3)

print("Matrix:\n", my_matrix)

print("Type:", type(my_matrix))


Matrix:
 [[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>


In [5]:
import numpy as np
arr = np.empty((2, 2))

print("Array:\n", arr)
print("Type:", type(arr))

# np.empty creates an array without initializing its values.
# That means the memory is allocated, but the contents are whatever
# happens to already be in that memory location so the unpredictable values.
#
# 
# np.empty is faster because it skips the step of filling the array with zeros.
# It's useful when you plan to overwrite all elements immediately,
# 


Array:
 [[0.00000000e+000 1.51344509e-311]
 [1.51344509e-311 1.51344509e-311]]
Type: <class 'numpy.ndarray'>


In [7]:
import numpy as np
matrix = np.random.random((3,3))

print("Random 3x3 Matrix:\n", matrix)
print("Type:", type(matrix))
print("type:",type(matrix++









































                   

Random 3x3 Matrix:
 [[0.58696877 0.38239799 0.59554742]
 [0.22150986 0.65408241 0.86021809]
 [0.17797084 0.16332359 0.97199533]]
Type: <class 'numpy.ndarray'>
